language: objective-c
xcode_project: XTSafeCollection.xcodeproj
xcode_scheme: XTSafeCollection
osx_image: xcode7

script: xcodebuild -project XTSafeCollection.xcodeproj -scheme XTSafeCollection -sdk iphonesimulator test
